driver:
  bend_range_deg:
  - 100.0
  - -30.0
  filter_alpha: 0.2
  output_deadband_deg: 1.5
  fingers:
    index:
      invert_side: false
      motor1_offset: 0.0
      motor2_offset: 0.0
    middle:
      invert_side: false
      motor1_offset: 0.0
      motor2_offset: 0.0
    ring:
      invert_side: true
      motor1_offset: 0.0
      motor2_offset: 0.0
    thumb:
      invert_side: false
      motor1_offset: 0.0
      motor2_offset: 0.0
  side_range_deg:
  - -20.0
  - 20.0
  thumb_side_range_deg:
  - 0.0
  - 45.0
hardware:
  angle_limit_max: 150.0
  angle_limit_min: -150.0
  baudrate: 1000000
  motors:
  - finger: index
    motor1_id: 1
    motor1_invert: false
    motor1_offset_rad: 0.12217304763960307
    motor2_id: 2
    motor2_invert: false
    motor2_offset_rad: 0.08726646259971647
  - finger: middle
    motor1_id: 3
    motor1_invert: false
    motor1_offset_rad: 0.0
    motor2_id: 4
    motor2_invert: false
    motor2_offset_rad: 0.12217304763960307
  - finger: ring
    motor1_id: 5
    motor1_invert: false
    motor1_offset_rad: 0.08726646259971647
    motor2_id: 6
    motor2_invert: false
    motor2_offset_rad: 0.12217304763960307
  - finger: thumb
    motor1_id: 7
    motor1_invert: false
    motor1_offset_rad: 0.0
    motor2_id: 8
    motor2_invert: false
    motor2_offset_rad: 0.12217304763960307
  on_connect_fail: warn
  serial_port: /dev/ttyACM0
  timeout_ms: 10
mode: both
mujoco:
  target_fps: 60
  xml_path: /home/user/robot_ws/AmazingHand-main/Demo/AHSimulation/AHSimulation/AH_Left/mjcf/scene.xml
vision:
  camera_index: 0
  deadband_bend: 0.002
  deadband_side: 0.002
  fingers:
    index:
      bend_range:
      - -0.0351
      - 0.064
      spread_range:
      - -0.0449
      - 0.0005
    middle:
      bend_range:
      - -0.0315
      - 0.0741
      spread_range:
      - -0.0432
      - -0.012
    ring:
      bend_range:
      - -0.0321
      - 0.0688
      spread_range:
      - -0.0363
      - -0.0101
    thumb:
      bend_range:
      - 0.00
      - 0.10
      spread_range:
      - -0.05
      - 0.05
  fps: 30
  frame_height: 480
  frame_width: 640
  mediapipe_model_complexity: 0
  min_detection_confidence: 0.7
  min_tracking_confidence: 0.5
